
use its2026;

drop table if exists games;

create table games(
    game_id int primary key auto_increment,
    nome varchar(100),
    genere varchar(100),
    publisher varchar(100),
    platform varchar(100),
    year int check (year > 1960)
);

insert into games (nome, genere, publisher, platform, year) values ('The Oregon Trail', 'Strategy', 'MECC', 'HP 2100', 1971);
insert into games (nome, genere, publisher, platform, year) values ('Pong', 'Sports', 'Atari, Inc.', 'Arcade', 1972);
insert into games (nome, genere, publisher, platform, year) values ('Combat', 'Top-down shooter', 'Atari, Inc.', 'Atari 2600', 1977);
insert into games (nome, genere, publisher, platform, year) values ('Zork', 'Adventure', 'Infocom', 'PDP-10', 1977);
insert into games (nome, genere, publisher, platform, year) values ('Space Invaders', 'Shoot \'em up', 'Taito', 'Arcade', 1978);
insert into games (nome, genere, publisher, platform, year) values ('Asteroids', 'Shoot \'em up', 'Atari, Inc.', 'Arcade', 1979);
insert into games (nome, genere, publisher, platform, year) values ('Adventure', 'Action-adventure', 'Atari, Inc.', 'Atari 2600', 1980);
insert into games (nome, genere, publisher, platform, year) values ('Battlezone', 'Vehicle simulation', 'Atari, Inc.', 'Arcade', 1980);
insert into games (nome, genere, publisher, platform, year) values ('Missile Command', 'Shoot \'em up', 'Atari, Inc.', 'Arcade', 1980);
insert into games (nome, genere, publisher, platform, year) values ('Pac-Man', 'Maze', 'Namco', 'Arcade', 1980);
insert into games (nome, genere, publisher, platform, year) values ('Centipede', 'Shoot \'em up', 'Atari, Inc.', 'Arcade', 1981);
insert into games (nome, genere, publisher, platform, year) values ('Defender', 'Shoot \'em up', 'Williams Entertainment', 'Arcade', 1981);
insert into games (nome, genere, publisher, platform, year) values ('Donkey Kong', 'Platform', 'Nintendo', 'Arcade', 1981);
insert into games (nome, genere, publisher, platform, year) values ('Frogger', 'Action', 'Konami/Sega', 'Arcade', 1981);
insert into games (nome, genere, publisher, platform, year) values ('Galaga', 'Shoot \'em up', 'Namco', 'Arcade', 1981);
insert into games (nome, genere, publisher, platform, year) values ('Tempest', 'Shoot \'em up', 'Atari, Inc.', 'Arcade', 1981);
insert into games (nome, genere, publisher, platform, year) values ('Wizardry: Proving Grounds of the Mad Overlord', 'Role-playing', 'Sir-Tech', 'Apple II', 1981);
insert into games (nome, genere, publisher, platform, year) values ('Joust', 'Action', 'Williams', 'Arcade', 1982);
insert into games (nome, genere, publisher, platform, year) values ('Ms. Pac-Man', 'Maze', 'Midway', 'Arcade', 1982);
insert into games (nome, genere, publisher, platform, year) values ('Pitfall!', 'Platform', 'Activision', 'Atari 2600', 1982);
insert into games (nome, genere, publisher, platform, year) values ('Robotron: 2084', 'Top-down shooter', 'Williams', 'Arcade', 1982);
insert into games (nome, genere, publisher, platform, year) values ('Archon: The Light and the Dark', 'Strategy', 'Electronic Arts', 'Atari 8-bit family', 1983);
insert into games (nome, genere, publisher, platform, year) values ('Lode Runner', 'Platform', 'Broderbund', 'Apple II', 1983);
insert into games (nome, genere, publisher, platform, year) values ('M.U.L.E.', 'Business simulation', 'Electronic Arts', 'Atari 8-bit family', 1983);
insert into games (nome, genere, publisher, platform, year) values ('Star Wars', 'Shoot \'em up', 'Atari, Inc.', 'Arcade', 1983);
insert into games (nome, genere, publisher, platform, year) values ('Elite', 'Space flight simulator', 'Acornsoft', 'BBC Micro', 1984);
insert into games (nome, genere, publisher, platform, year) values ('Marble Madness', 'Action', 'Atari Games', 'Arcade', 1984);
insert into games (nome, genere, publisher, platform, year) values ('Tetris', 'Puzzle', 'Elorg', 'Electronika 60', 1984);
insert into games (nome, genere, publisher, platform, year) values ('Gauntlet', 'Action role-playing', 'Atari Games', 'Arcade', 1985);
insert into games (nome, genere, publisher, platform, year) values ('Ghosts \'n Goblins', 'Platform', 'Capcom', 'Arcade', 1985);
insert into games (nome, genere, publisher, platform, year) values ('Super Mario Bros.', 'Platform', 'Nintendo', 'NES', 1985);
insert into games (nome, genere, publisher, platform, year) values ('Ultima IV: Quest of the Avatar', 'Role-playing', 'Origin Systems', 'Apple II', 1985);
insert into games (nome, genere, publisher, platform, year) values ('Arkanoid', 'Block breaker', 'Taito', 'Arcade', 1986);
insert into games (nome, genere, publisher, platform, year) values ('Bubble Bobble', 'Platform', 'Taito', 'Arcade', 1986);
insert into games (nome, genere, publisher, platform, year) values ('The Legend of Zelda', 'Action-adventure', 'Nintendo', 'NES', 1986);
insert into games (nome, genere, publisher, platform, year) values ('Out Run', 'Racing', 'Sega', 'Arcade', 1986);
insert into games (nome, genere, publisher, platform, year) values ('Contra', 'Run and gun', 'Konami', 'Arcade', 1987);
insert into games (nome, genere, publisher, platform, year) values ('Double Dragon', 'Beat \'em up', 'Technos Japan', 'Arcade', 1987);
insert into games (nome, genere, publisher, platform, year) values ('Dungeon Master', 'Role-playing', 'FTL Games', 'Atari ST', 1987);
insert into games (nome, genere, publisher, platform, year) values ('Mike Tyson\'s Punch-Out!!', 'Sports', 'Nintendo', 'NES', 1987);
insert into games (nome, genere, publisher, platform, year) values ('R-Type', 'Shoot \'em up', 'Irem', 'Arcade', 1987);
insert into games (nome, genere, publisher, platform, year) values ('Sid Meier\'s Pirates!', 'Action-adventure', 'MicroProse', 'Commodore 64', 1987);
insert into games (nome, genere, publisher, platform, year) values ('Mega Man 2', 'Platform', 'Capcom', 'NES', 1988);
insert into games (nome, genere, publisher, platform, year) values ('Ninja Gaiden', 'Platform', 'Tecmo', 'NES', 1988);
insert into games (nome, genere, publisher, platform, year) values ('Super Mario Bros. 3', 'Platform', 'Nintendo', 'NES', 1988);
insert into games (nome, genere, publisher, platform, year) values ('Final Fight', 'Beat \'em up', 'Capcom', 'Arcade', 1989);
insert into games (nome, genere, publisher, platform, year) values ('Populous', 'God game', 'Electronic Arts', 'Amiga', 1989);
insert into games (nome, genere, publisher, platform, year) values ('Prince of Persia', 'Platform', 'Broderbund', 'Apple II', 1989);
insert into games (nome, genere, publisher, platform, year) values ('SimCity', 'City-building', 'Maxis', 'Amiga, Macintosh', 1989);
insert into games (nome, genere, publisher, platform, year) values ('The Secret of Monkey Island', 'Adventure', 'LucasArts', 'PC', 1990);
insert into games (nome, genere, publisher, platform, year) values ('Speedball 2: Brutal Deluxe', 'Sports', 'Image Works', 'Atari ST', 1990);
insert into games (nome, genere, publisher, platform, year) values ('Super Mario World', 'Platform', 'Nintendo', 'Super NES', 1990);
insert into games (nome, genere, publisher, platform, year) values ('Wing Commander', 'Space flight simulator', 'Origin Systems', 'PC', 1990);
insert into games (nome, genere, publisher, platform, year) values ('Another World', 'Platform', 'Delphine Software', 'Amiga, Atari ST', 1991);
insert into games (nome, genere, publisher, platform, year) values ('Civilization', 'Turn-based strategy', 'MicroProse', 'PC', 1991);
insert into games (nome, genere, publisher, platform, year) values ('Final Fantasy IV', 'Role-playing', 'Square', 'Super NES', 1991);
insert into games (nome, genere, publisher, platform, year) values ('The Legend of Zelda: A Link to the Past', 'Action-adventure', 'Nintendo', 'Super NES', 1991);
insert into games (nome, genere, publisher, platform, year) values ('Lemmings', 'Puzzle', 'Psygnosis', 'Amiga', 1991);
insert into games (nome, genere, publisher, platform, year) values ('Micro Machines', 'Racing', 'Camerica', 'NES', 1991);
insert into games (nome, genere, publisher, platform, year) values ('Monkey Island 2: LeChuck\'s Revenge', 'Adventure', 'LucasArts', 'PC', 1991);
insert into games (nome, genere, publisher, platform, year) values ('Sonic the Hedgehog', 'Platform', 'Sega', 'Sega Genesis', 1991);
insert into games (nome, genere, publisher, platform, year) values ('Street Fighter II', 'Fighting', 'Capcom', 'Arcade', 1991);
insert into games (nome, genere, publisher, platform, year) values ('Super Castlevania IV', 'Platform', 'Konami', 'Super NES', 1991);
insert into games (nome, genere, publisher, platform, year) values ('Alone in the Dark', 'Survival horror', 'Infogrames', 'PC', 1992);
insert into games (nome, genere, publisher, platform, year) values ('Contra III: The Alien Wars', 'Run and gun', 'Konami', 'Super NES', 1992);
insert into games (nome, genere, publisher, platform, year) values ('Dune II', 'Real-time strategy', 'Virgin Games', 'PC', 1992);
insert into games (nome, genere, publisher, platform, year) values ('Flashback', 'Platform', 'U.S. Gold', 'Amiga', 1992);
insert into games (nome, genere, publisher, platform, year) values ('Indiana Jones and the Fate of Atlantis', 'Adventure', 'LucasArts', 'PC', 1992);
insert into games (nome, genere, publisher, platform, year) values ('Mortal Kombat', 'Fighting', 'Midway', 'Arcade', 1992);
insert into games (nome, genere, publisher, platform, year) values ('Sensible Soccer', 'Sports', 'Renegade Software', 'Amiga, Atari ST', 1992);
insert into games (nome, genere, publisher, platform, year) values ('Sonic the Hedgehog 2', 'Platform', 'Sega', 'Sega Genesis', 1992);
insert into games (nome, genere, publisher, platform, year) values ('Star Control II', 'Action-adventure', 'Accolade', 'PC', 1992);
insert into games (nome, genere, publisher, platform, year) values ('Streets of Rage 2', 'Beat \'em up', 'Sega', 'Sega Genesis', 1992);
insert into games (nome, genere, publisher, platform, year) values ('Super Mario Kart', 'Kart racing', 'Nintendo', 'Super NES', 1992);
insert into games (nome, genere, publisher, platform, year) values ('Ultima VII: The Black Gate', 'Role-playing', 'Origin Systems', 'PC', 1992);
insert into games (nome, genere, publisher, platform, year) values ('Virtua Racing', 'Racing', 'Sega', 'Arcade', 1992);
insert into games (nome, genere, publisher, platform, year) values ('Wolfenstein 3D', 'First-person shooter', 'Apogee Software', 'PC', 1992);
insert into games (nome, genere, publisher, platform, year) values ('Day of the Tentacle', 'Adventure', 'LucasArts', 'PC', 1993);
insert into games (nome, genere, publisher, platform, year) values ('Daytona USA', 'Racing', 'Sega', 'Arcade', 1993);
insert into games (nome, genere, publisher, platform, year) values ('Doom', 'First-person shooter', 'id Software', 'PC', 1993);
insert into games (nome, genere, publisher, platform, year) values ('Gunstar Heroes', 'Run and gun', 'Sega', 'Sega Genesis', 1993);
insert into games (nome, genere, publisher, platform, year) values ('The Legend of Zelda: Link\'s Awakening', 'Action-adventure', 'Nintendo', 'Game Boy', 1993);
insert into games (nome, genere, publisher, platform, year) values ('Mega Man X', 'Platform', 'Capcom', 'Super NES', 1993);
insert into games (nome, genere, publisher, platform, year) values ('Mortal Kombat II', 'Fighting', 'Midway', 'Arcade', 1993);
insert into games (nome, genere, publisher, platform, year) values ('Myst', 'Adventure', 'Broderbund', 'Macintosh', 1993);
insert into games (nome, genere, publisher, platform, year) values ('NBA Jam', 'Sports', 'Midway', 'Arcade', 1993);
insert into games (nome, genere, publisher, platform, year) values ('Phantasy Star IV', 'Role-playing', 'Sega', 'Sega Genesis', 1993);
insert into games (nome, genere, publisher, platform, year) values ('Ridge Racer', 'Racing', 'Namco', 'Arcade', 1993);
insert into games (nome, genere, publisher, platform, year) values ('Sam & Max Hit the Road', 'Adventure', 'LucasArts', 'PC', 1993);
insert into games (nome, genere, publisher, platform, year) values ('Secret of Mana', 'Action role-playing', 'Square', 'Super NES', 1993);
insert into games (nome, genere, publisher, platform, year) values ('Samurai Shodown', 'Fighting', 'SNK', 'Arcade', 1993);
insert into games (nome, genere, publisher, platform, year) values ('SimCity 2000', 'City-building', 'Maxis', 'Macintosh', 1993);
insert into games (nome, genere, publisher, platform, year) values ('Star Fox', 'Shoot \'em up', 'Nintendo', 'Super NES', 1993);
insert into games (nome, genere, publisher, platform, year) values ('Syndicate', 'Real-time tactics', 'Electronic Arts', 'Amiga, PC', 1993);
insert into games (nome, genere, publisher, platform, year) values ('Donkey Kong Country', 'Platform', 'Nintendo', 'Super NES', 1994);
insert into games (nome, genere, publisher, platform, year) values ('Doom II', 'First-person shooter', 'GT Interactive', 'PC', 1994);
insert into games (nome, genere, publisher, platform, year) values ('EarthBound', 'Role-playing', 'Nintendo', 'Super NES', 1994);
insert into games (nome, genere, publisher, platform, year) values ('Final Fantasy VI', 'Role-playing', 'Square', 'Super NES', 1994);
insert into games (nome, genere, publisher, platform, year) values ('Sega Rally Championship', 'Racing', 'Sega', 'Arcade', 1994);
insert into games (nome, genere, publisher, platform, year) values ('Sensible World of Soccer', 'Sports', 'Renegade Software', 'Amiga', 1994);
insert into games (nome, genere, publisher, platform, year) values ('Star Wars: TIE Fighter', 'Space flight simulator', 'LucasArts', 'PC', 1994);
insert into games (nome, genere, publisher, platform, year) values ('Super Metroid', 'Action-adventure', 'Nintendo', 'Super NES', 1994);
insert into games (nome, genere, publisher, platform, year) values ('Tempest 2000', 'Shoot \'em up', 'Atari Corporation', 'Atari Jaguar', 1994);
insert into games (nome, genere, publisher, platform, year) values ('Theme Park', 'Business simulation', 'Electronic Arts', 'Amiga, PC', 1994);
insert into games (nome, genere, publisher, platform, year) values ('Virtua Fighter 2', 'Fighting', 'Sega', 'Arcade', 1994);
insert into games (nome, genere, publisher, platform, year) values ('X-COM: UFO Defense', 'Turn-based strategy', 'MicroProse', 'PC', 1994);
insert into games (nome, genere, publisher, platform, year) values ('Chrono Trigger', 'Role-playing', 'Square', 'Super NES', 1995);
insert into games (nome, genere, publisher, platform, year) values ('Command & Conquer', 'Real-time strategy', 'Virgin Interactive', 'PC', 1995);
insert into games (nome, genere, publisher, platform, year) values ('MechWarrior 2: 31st Century Combat', 'Vehicle simulation', 'Activision', 'PC', 1995);
insert into games (nome, genere, publisher, platform, year) values ('Warcraft II: Tides of Darkness', 'Real-time strategy', 'Blizzard Entertainment', 'PC', 1995);
insert into games (nome, genere, publisher, platform, year) values ('Wipeout', 'Racing', 'Psygnosis', 'PC, PlayStation', 1995);
insert into games (nome, genere, publisher, platform, year) values ('Worms', 'Artillery', 'Ocean Software', 'Amiga', 1995);
insert into games (nome, genere, publisher, platform, year) values ('Yoshi\'s Island', 'Platform', 'Nintendo', 'Super NES', 1995);
insert into games (nome, genere, publisher, platform, year) values ('Civilization II', 'Turn-based strategy', 'MicroProse', 'PC', 1996);
insert into games (nome, genere, publisher, platform, year) values ('Command & Conquer: Red Alert', 'Real-time strategy', 'Virgin Interactive', 'PC', 1996);
insert into games (nome, genere, publisher, platform, year) values ('Duke Nukem 3D', 'First-person shooter', 'GT Interactive', 'PC', 1996);
insert into games (nome, genere, publisher, platform, year) values ('Mario Kart 64', 'Kart racing', 'Nintendo', 'Nintendo 64', 1996);
insert into games (nome, genere, publisher, platform, year) values ('Nights into Dreams...', 'Action', 'Sega', 'Saturn', 1996);
insert into games (nome, genere, publisher, platform, year) values ('PaRappa the Rapper', 'Rhythm', 'Sony Computer Entertainment', 'PlayStation', 1996);
insert into games (nome, genere, publisher, platform, year) values ('Pokémon Redand Blue', 'Role-playing', 'Nintendo', 'Game Boy', 1996);
insert into games (nome, genere, publisher, platform, year) values ('Quake', 'First-person shooter', 'GT Interactive', 'PC', 1996);
insert into games (nome, genere, publisher, platform, year) values ('Resident Evil', 'Survival horror', 'Capcom', 'PlayStation', 1996);
insert into games (nome, genere, publisher, platform, year) values ('Super Mario 64', 'Platform', 'Nintendo', 'Nintendo 64', 1996);
insert into games (nome, genere, publisher, platform, year) values ('Tekken 3', 'Fighting', 'Namco', 'Arcade', 1996);
insert into games (nome, genere, publisher, platform, year) values ('Tomb Raider', 'Action-adventure', 'Eidos Interactive', 'Saturn, PC, PlayStation', 1996);
insert into games (nome, genere, publisher, platform, year) values ('Wave Race 64', 'Racing', 'Nintendo', 'Nintendo 64', 1996);
insert into games (nome, genere, publisher, platform, year) values ('Wipeout 2097', 'Racing', 'Psygnosis', 'PlayStation', 1996);
insert into games (nome, genere, publisher, platform, year) values ('Age of Empires', 'Real-time strategy', 'Microsoft', 'PC', 1997);
insert into games (nome, genere, publisher, platform, year) values ('Castlevania: Symphony of the Night', 'Action-adventure', 'Konami', 'PlayStation', 1997);
insert into games (nome, genere, publisher, platform, year) values ('Diablo', 'Action role-playing', 'Blizzard Entertainment', 'PC', 1997);
insert into games (nome, genere, publisher, platform, year) values ('Fallout', 'Role-playing', 'Interplay Entertainment', 'PC', 1997);
insert into games (nome, genere, publisher, platform, year) values ('Final Fantasy Tactics', 'Tactical role-playing', 'Square', 'PlayStation', 1997);
insert into games (nome, genere, publisher, platform, year) values ('Final Fantasy VII', 'Role-playing', 'Square', 'PlayStation', 1997);
insert into games (nome, genere, publisher, platform, year) values ('GoldenEye 007', 'First-person shooter', 'Nintendo', 'Nintendo 64', 1997);
insert into games (nome, genere, publisher, platform, year) values ('Gran Turismo', 'Racing', 'Sony Computer Entertainment', 'PlayStation', 1997);
insert into games (nome, genere, publisher, platform, year) values ('Grand Theft Auto', 'Action-adventure', 'BMG Interactive', 'PC', 1997);
insert into games (nome, genere, publisher, platform, year) values ('Quake II', 'First-person shooter', 'Activision', 'PC', 1997);
insert into games (nome, genere, publisher, platform, year) values ('Star Fox 64', 'Shoot \'em up', 'Nintendo', 'Nintendo 64', 1997);
insert into games (nome, genere, publisher, platform, year) values ('Star Wars Jedi Knight: Dark Forces II', 'First-person shooter', 'LucasArts', 'PC', 1997);
insert into games (nome, genere, publisher, platform, year) values ('Total Annihilation', 'Real-time strategy', 'Cavedog Entertainment', 'PC', 1997);
insert into games (nome, genere, publisher, platform, year) values ('Ultima Online', 'MMORPG', 'Electronic Arts', 'PC', 1997);
insert into games (nome, genere, publisher, platform, year) values ('Baldur\'s Gate', 'Role-playing', 'Black Isle Studios', 'PC', 1998);
insert into games (nome, genere, publisher, platform, year) values ('Crash Bandicoot: Warped', 'Platform', 'Sony Computer Entertainment', 'PlayStation', 1998);
insert into games (nome, genere, publisher, platform, year) values ('Dance Dance Revolution', 'Rhythm', 'Konami', 'Arcade', 1998);
insert into games (nome, genere, publisher, platform, year) values ('Fallout 2', 'Role-playing', 'Interplay Entertainment', 'PC', 1998);
insert into games (nome, genere, publisher, platform, year) values ('Grim Fandango', 'Adventure', 'LucasArts', 'PC', 1998);
insert into games (nome, genere, publisher, platform, year) values ('Half-Life', 'First-person shooter', 'Sierra Studios', 'PC', 1998);
insert into games (nome, genere, publisher, platform, year) values ('The Legend of Zelda: Ocarina of Time', 'Action-adventure', 'Nintendo', 'Nintendo 64', 1998);
insert into games (nome, genere, publisher, platform, year) values ('Metal Gear Solid', 'Stealth', 'Konami', 'PlayStation', 1998);
insert into games (nome, genere, publisher, platform, year) values ('Panzer Dragoon Saga', 'Role-playing', 'Sega', 'Saturn', 1998);
insert into games (nome, genere, publisher, platform, year) values ('Resident Evil 2', 'Survival horror', 'Capcom', 'PlayStation', 1998);
insert into games (nome, genere, publisher, platform, year) values ('Soulcalibur', 'Fighting', 'Namco', 'Arcade', 1998);
insert into games (nome, genere, publisher, platform, year) values ('StarCraft', 'Real-time strategy', 'Blizzard Entertainment', 'PC', 1998);
insert into games (nome, genere, publisher, platform, year) values ('Suikoden II', 'Role-playing', 'Konami', 'PlayStation', 1998);
insert into games (nome, genere, publisher, platform, year) values ('Thief: The Dark Project', 'Stealth', 'Eidos Interactive', 'PC', 1998);
insert into games (nome, genere, publisher, platform, year) values ('Age of Empires II', 'Real-time strategy', 'Microsoft', 'PC', 1999);
insert into games (nome, genere, publisher, platform, year) values ('EverQuest', 'MMORPG', 'Sony Online Entertainment', 'PC', 1999);
insert into games (nome, genere, publisher, platform, year) values ('Homeworld', 'Real-time strategy', 'Sierra Studios', 'PC', 1999);
insert into games (nome, genere, publisher, platform, year) values ('Planescape: Torment', 'Role-playing', 'Interplay Entertainment', 'PC', 1999);
insert into games (nome, genere, publisher, platform, year) values ('Pokémon Goldand Silver', 'Role-playing', 'Nintendo', 'Game Boy Color', 1999);
insert into games (nome, genere, publisher, platform, year) values ('Quake III: Arena', 'First-person shooter', 'Activision', 'PC', 1999);
insert into games (nome, genere, publisher, platform, year) values ('Shenmue', 'Adventure', 'Sega', 'Dreamcast', 1999);
insert into games (nome, genere, publisher, platform, year) values ('Silent Hill', 'Survival horror', 'Konami', 'PlayStation', 1999);
insert into games (nome, genere, publisher, platform, year) values ('System Shock 2', 'First-person shooter', 'Electronic Arts', 'PC', 1999);
insert into games (nome, genere, publisher, platform, year) values ('Unreal Tournament', 'First-person shooter', 'GT Interactive', 'PC', 1999);
insert into games (nome, genere, publisher, platform, year) values ('Baldur\'s Gate II: Shadows of Amn', 'Role-playing', 'Black Isle Studios', 'PC', 2000);
insert into games (nome, genere, publisher, platform, year) values ('Counter-Strike', 'First-person shooter', 'Valve', 'PC', 2000);
insert into games (nome, genere, publisher, platform, year) values ('Deus Ex', 'Action role-playing', 'Eidos Interactive', 'PC', 2000);
insert into games (nome, genere, publisher, platform, year) values ('Diablo II', 'Action role-playing', 'Blizzard Entertainment', 'PC', 2000);
insert into games (nome, genere, publisher, platform, year) values ('Jet Set Radio', 'Platform', 'Sega', 'Dreamcast', 2000);
insert into games (nome, genere, publisher, platform, year) values ('The Legend of Zelda: Majora\'s Mask', 'Action-adventure', 'Nintendo', 'Nintendo 64', 2000);
insert into games (nome, genere, publisher, platform, year) values ('Marvel vs. Capcom 2: New Age of Heroes', 'Fighting', 'Capcom', 'Arcade', 2000);
insert into games (nome, genere, publisher, platform, year) values ('The Sims', 'Life simulation', 'Electronic Arts', 'PC', 2000);
insert into games (nome, genere, publisher, platform, year) values ('Thief II: The Metal Age', 'Stealth', 'Eidos Interactive', 'PC', 2000);
insert into games (nome, genere, publisher, platform, year) values ('Tony Hawk\'s Pro Skater 2', 'Sports', 'Activision', 'PlayStation', 2000);
insert into games (nome, genere, publisher, platform, year) values ('Advance Wars', 'Turn-based tactics', 'Nintendo', 'Game Boy Advance', 2001);
insert into games (nome, genere, publisher, platform, year) values ('Animal Crossing', 'Life simulation', 'Nintendo', 'GameCube', 2001);
insert into games (nome, genere, publisher, platform, year) values ('Devil May Cry', 'Action-adventure', 'Capcom', 'PlayStation 2', 2001);
insert into games (nome, genere, publisher, platform, year) values ('Final Fantasy X', 'Role-playing', 'Square', 'PlayStation 2', 2001);
insert into games (nome, genere, publisher, platform, year) values ('Gran Turismo 3: A-Spec', 'Racing', 'Sony Computer Entertainment', 'PlayStation 2', 2001);
insert into games (nome, genere, publisher, platform, year) values ('Grand Theft Auto III', 'Action-adventure', 'Rockstar Games', 'PlayStation 2', 2001);
insert into games (nome, genere, publisher, platform, year) values ('Halo: Combat Evolved', 'First-person shooter', 'Microsoft Game Studios', 'Xbox', 2001);
insert into games (nome, genere, publisher, platform, year) values ('Ico', 'Action-adventure', 'Sony Computer Entertainment', 'PlayStation 2', 2001);
insert into games (nome, genere, publisher, platform, year) values ('Ikaruga', 'Shoot \'em up', 'Treasure', 'Arcade', 2001);
insert into games (nome, genere, publisher, platform, year) values ('Max Payne', 'Third-person shooter', 'Gathering of Developers', 'PC', 2001);
insert into games (nome, genere, publisher, platform, year) values ('Metal Gear Solid 2: Sons of Liberty', 'Stealth', 'Konami', 'PlayStation 2', 2001);
insert into games (nome, genere, publisher, platform, year) values ('Phoenix Wright: Ace Attorney', 'Adventure', 'Capcom', 'Game Boy Advance', 2001);
insert into games (nome, genere, publisher, platform, year) values ('Rez', 'Shoot \'em up', 'Sega', 'Dreamcast, PlayStation 2', 2001);
insert into games (nome, genere, publisher, platform, year) values ('Silent Hill 2', 'Survival horror', 'Konami', 'PlayStation 2', 2001);
insert into games (nome, genere, publisher, platform, year) values ('Super Smash Bros. Melee', 'Fighting', 'Nintendo', 'GameCube', 2001);
insert into games (nome, genere, publisher, platform, year) values ('Tony Hawk\'s Pro Skater 3', 'Sports', 'Activision', 'PlayStation, PlayStation 2', 2001);
insert into games (nome, genere, publisher, platform, year) values ('Battlefield 1942', 'First-person shooter', 'Electronic Arts', 'PC', 2002);
insert into games (nome, genere, publisher, platform, year) values ('The Elder Scrolls III: Morrowind', 'Action role-playing', 'Bethesda Softworks', 'PC', 2002);
insert into games (nome, genere, publisher, platform, year) values ('Eternal Darkness: Sanity\'s Requiem', 'Survival horror', 'Nintendo', 'GameCube', 2002);
insert into games (nome, genere, publisher, platform, year) values ('Grand Theft Auto: Vice City', 'Action-adventure', 'Rockstar Games', 'PlayStation 2', 2002);
insert into games (nome, genere, publisher, platform, year) values ('Kingdom Hearts', 'Action role-playing', 'Square', 'PlayStation 2', 2002);
insert into games (nome, genere, publisher, platform, year) values ('The Legend of Zelda: The Wind Waker', 'Action-adventure', 'Nintendo', 'GameCube', 2002);
insert into games (nome, genere, publisher, platform, year) values ('Metroid Prime', 'Action-adventure', 'Nintendo', 'GameCube', 2002);
insert into games (nome, genere, publisher, platform, year) values ('Soulcalibur II', 'Fighting', 'Namco', 'Arcade', 2002);
insert into games (nome, genere, publisher, platform, year) values ('Tom Clancy\'s Splinter Cell', 'Stealth', 'Ubisoft', 'Xbox', 2002);
insert into games (nome, genere, publisher, platform, year) values ('Warcraft III: Reign of Chaos', 'Real-time strategy', 'Blizzard Entertainment', 'PC, Macintosh', 2002);
insert into games (nome, genere, publisher, platform, year) values ('Beyond Good & Evil', 'Action-adventure', 'Ubisoft', 'PlayStation 2', 2003);
insert into games (nome, genere, publisher, platform, year) values ('F-Zero GX', 'Racing', 'Nintendo', 'GameCube', 2003);
insert into games (nome, genere, publisher, platform, year) values ('Max Payne 2: The Fall of Max Payne', 'Third-person shooter', 'Rockstar Games', 'PC', 2003);
insert into games (nome, genere, publisher, platform, year) values ('Prince of Persia: The Sands of Time', 'Action-adventure', 'Ubisoft', 'PlayStation 2', 2003);
insert into games (nome, genere, publisher, platform, year) values ('Star Wars: Knights of the Old Republic', 'Role-playing', 'LucasArts', 'Xbox', 2003);
insert into games (nome, genere, publisher, platform, year) values ('WarioWare, Inc.: Mega Microgames!', 'Action', 'Nintendo', 'Game Boy Advance', 2003);
insert into games (nome, genere, publisher, platform, year) values ('Burnout 3: Takedown', 'Racing', 'Electronic Arts', 'PlayStation 2, Xbox', 2004);
insert into games (nome, genere, publisher, platform, year) values ('The Chronicles of Riddick: Escape from Butcher Bay', 'Stealth', 'Vivendi Universal Games', 'Xbox', 2004);
insert into games (nome, genere, publisher, platform, year) values ('Dragon Quest VIII', 'Role-playing', 'Square Enix', 'PlayStation 2', 2004);
insert into games (nome, genere, publisher, platform, year) values ('Gran Turismo 4', 'Racing', 'Sony Computer Entertainment', 'PlayStation 2', 2004);
insert into games (nome, genere, publisher, platform, year) values ('Grand Theft Auto: San Andreas', 'Action-adventure', 'Rockstar Games', 'PlayStation 2', 2004);
insert into games (nome, genere, publisher, platform, year) values ('Half-Life 2', 'First-person shooter', 'Valve', 'PC', 2004);
insert into games (nome, genere, publisher, platform, year) values ('Halo 2', 'First-person shooter', 'Microsoft Game Studios', 'Xbox', 2004);
insert into games (nome, genere, publisher, platform, year) values ('Katamari Damacy', 'Action', 'Namco', 'PlayStation 2', 2004);
insert into games (nome, genere, publisher, platform, year) values ('Metal Gear Solid 3: Snake Eater', 'Stealth', 'Konami', 'PlayStation 2', 2004);
insert into games (nome, genere, publisher, platform, year) values ('Rome: Total War', 'Strategy', 'Activision', 'PC', 2004);
insert into games (nome, genere, publisher, platform, year) values ('The Sims 2', 'Life simulation', 'Electronic Arts', 'PC', 2004);
insert into games (nome, genere, publisher, platform, year) values ('World of Warcraft', 'MMORPG', 'Blizzard Entertainment', 'PC, Macintosh', 2004);
insert into games (nome, genere, publisher, platform, year) values ('Call of Duty 2', 'First-person shooter', 'Activision', 'PC', 2005);
insert into games (nome, genere, publisher, platform, year) values ('Civilization IV', 'Turn-based strategy', '2K Games', 'PC', 2005);
insert into games (nome, genere, publisher, platform, year) values ('Devil May Cry 3: Dante\'s Awakening', 'Action-adventure', 'Capcom', 'PlayStation 2', 2005);
insert into games (nome, genere, publisher, platform, year) values ('God of War', 'Action-adventure', 'Sony Computer Entertainment', 'PlayStation 2', 2005);
insert into games (nome, genere, publisher, platform, year) values ('Guitar Hero', 'Rhythm', 'RedOctane', 'PlayStation 2', 2005);
insert into games (nome, genere, publisher, platform, year) values ('Psychonauts', 'Platform', 'Majesco', 'PC, Xbox', 2005);
insert into games (nome, genere, publisher, platform, year) values ('Resident Evil 4', 'Survival horror', 'Capcom', 'GameCube', 2005);
insert into games (nome, genere, publisher, platform, year) values ('Shadow of the Colossus', 'Action-adventure', 'Sony Computer Entertainment', 'PlayStation 2', 2005);
insert into games (nome, genere, publisher, platform, year) values ('Tom Clancy\'s Splinter Cell: Chaos Theory', 'Stealth', 'Ubisoft', 'GameCube, PC, PlayStation 2, Xbox', 2005);
insert into games (nome, genere, publisher, platform, year) values ('Company of Heroes', 'Real-time strategy', 'THQ', 'PC', 2006);
insert into games (nome, genere, publisher, platform, year) values ('The Elder Scrolls IV: Oblivion', 'Action role-playing', '2K Games, Bethesda Softworks', 'PC, Xbox 360', 2006);
insert into games (nome, genere, publisher, platform, year) values ('Gears of War', 'Third-person shooter', 'Microsoft Game Studios', 'Xbox 360', 2006);
insert into games (nome, genere, publisher, platform, year) values ('Hitman: Blood Money', 'Stealth', 'Eidos Interactive', 'PC, PlayStation 2, Xbox, Xbox 360', 2006);
insert into games (nome, genere, publisher, platform, year) values ('The Legend of Zelda: Twilight Princess', 'Action-adventure', 'Nintendo', 'GameCube, Wii', 2006);
insert into games (nome, genere, publisher, platform, year) values ('Ōkami', 'Action-adventure', 'Capcom', 'PlayStation 2', 2006);
insert into games (nome, genere, publisher, platform, year) values ('Wii Sports', 'Sports', 'Nintendo', 'Wii', 2006);
insert into games (nome, genere, publisher, platform, year) values ('BioShock', 'First-person shooter', '2K Games', 'PC, Xbox 360', 2007);
insert into games (nome, genere, publisher, platform, year) values ('Call of Duty 4: Modern Warfare', 'First-person shooter', 'Activision', 'PC, PlayStation 3, Xbox 360', 2007);
insert into games (nome, genere, publisher, platform, year) values ('God of War II', 'Action-adventure', 'Sony Computer Entertainment', 'PlayStation 2', 2007);
insert into games (nome, genere, publisher, platform, year) values ('Halo 3', 'First-person shooter', 'Microsoft Game Studios', 'Xbox 360', 2007);
insert into games (nome, genere, publisher, platform, year) values ('Mass Effect', 'Action role-playing', 'Microsoft Game Studios', 'Xbox 360', 2007);
insert into games (nome, genere, publisher, platform, year) values ('Portal', 'Puzzle-platformer', 'Valve', 'PC, Xbox 360', 2007);
insert into games (nome, genere, publisher, platform, year) values ('Rock Band', 'Rhythm', 'MTV Games', 'PlayStation 3, Xbox 360', 2007);
insert into games (nome, genere, publisher, platform, year) values ('Super Mario Galaxy', 'Platform', 'Nintendo', 'Wii', 2007);
insert into games (nome, genere, publisher, platform, year) values ('Team Fortress 2', 'First-person shooter', 'Valve', 'PC, Xbox 360', 2007);
insert into games (nome, genere, publisher, platform, year) values ('The World Ends with You', 'Role-playing', 'Square Enix', 'Nintendo DS', 2007);
insert into games (nome, genere, publisher, platform, year) values ('Braid', 'Puzzle-platformer', 'Microsoft Game Studios', 'Xbox 360', 2008);
insert into games (nome, genere, publisher, platform, year) values ('Burnout Paradise', 'Racing', 'Electronic Arts', 'PC, PlayStation 3, Xbox 360', 2008);
insert into games (nome, genere, publisher, platform, year) values ('Dead Space', 'Survival horror', 'Electronic Arts', 'PlayStation 3, Xbox 360', 2008);
insert into games (nome, genere, publisher, platform, year) values ('Fable II', 'Action role-playing', 'Microsoft Game Studios', 'Xbox 360', 2008);
insert into games (nome, genere, publisher, platform, year) values ('Fallout 3', 'Action role-playing', 'Bethesda Softworks', 'PC, PlayStation 3, Xbox 360', 2008);
insert into games (nome, genere, publisher, platform, year) values ('Gears of War 2', 'Third-person shooter', 'Microsoft Game Studios', 'Xbox 360', 2008);
insert into games (nome, genere, publisher, platform, year) values ('Grand Theft Auto IV', 'Action-adventure', 'Rockstar Games', 'PlayStation 3, Xbox 360', 2008);
insert into games (nome, genere, publisher, platform, year) values ('Left 4 Dead', 'First-person shooter', 'Valve', 'PC, Xbox 360', 2008);
insert into games (nome, genere, publisher, platform, year) values ('LittleBigPlanet', 'Platform', 'Sony Computer Entertainment', 'PlayStation 3', 2008);
insert into games (nome, genere, publisher, platform, year) values ('Persona 4', 'Role-playing', 'Atlus', 'PlayStation 2', 2008);
insert into games (nome, genere, publisher, platform, year) values ('Rock Band 2', 'Rhythm', 'MTV Games', 'Xbox 360', 2008);
insert into games (nome, genere, publisher, platform, year) values ('Spelunky', 'Platform', 'Derek Yu', 'PC', 2008);
insert into games (nome, genere, publisher, platform, year) values ('Street Fighter IV', 'Fighting', 'Capcom', 'Arcade', 2008);
insert into games (nome, genere, publisher, platform, year) values ('Valkyria Chronicles', 'Tactical role-playing', 'Sega', 'PlayStation 3', 2008);
insert into games (nome, genere, publisher, platform, year) values ('Angry Birds', 'Puzzle', 'Rovio Entertainment', 'Maemo, iOS', 2009);
insert into games (nome, genere, publisher, platform, year) values ('Assassin\'s Creed II', 'Action-adventure', 'Ubisoft', 'PlayStation 3, Xbox 360', 2009);
insert into games (nome, genere, publisher, platform, year) values ('Batman: Arkham Asylum', 'Action-adventure', 'Eidos Interactive, Warner Bros. Interactive Entertainment', 'PlayStation 3, Xbox 360', 2009);
insert into games (nome, genere, publisher, platform, year) values ('Bayonetta', 'Action', 'Sega', 'PlayStation 3, Xbox 360', 2009);
insert into games (nome, genere, publisher, platform, year) values ('Borderlands', 'Action role-playing', '2K Games', 'PC, PlayStation 3, Xbox 360', 2009);
insert into games (nome, genere, publisher, platform, year) values ('Demon\'s Souls', 'Action role-playing', 'Sony Computer Entertainment', 'PlayStation 3', 2009);
insert into games (nome, genere, publisher, platform, year) values ('Dragon Age: Origins', 'Role-playing', 'Electronic Arts', 'PC, PlayStation 3, Xbox 360', 2009);
insert into games (nome, genere, publisher, platform, year) values ('League of Legends', 'MOBA', 'Riot Games', 'PC', 2009);
insert into games (nome, genere, publisher, platform, year) values ('Left 4 Dead 2', 'First-person shooter', 'Valve', 'PC, Xbox 360', 2009);
insert into games (nome, genere, publisher, platform, year) values ('Plants vs. Zombies', 'Tower defense', 'PopCap Games', 'PC, Macintosh', 2009);
insert into games (nome, genere, publisher, platform, year) values ('Uncharted 2: Among Thieves', 'Action-adventure', 'Sony Computer Entertainment', 'PlayStation 3', 2009);
insert into games (nome, genere, publisher, platform, year) values ('God of War III', 'Action-adventure', 'Sony Computer Entertainment', 'PlayStation 3', 2010);
insert into games (nome, genere, publisher, platform, year) values ('Heavy Rain', 'Adventure', 'Sony Computer Entertainment', 'PlayStation 3', 2010);
insert into games (nome, genere, publisher, platform, year) values ('Limbo', 'Platform', 'Microsoft Game Studios', 'Xbox 360', 2010);
insert into games (nome, genere, publisher, platform, year) values ('Mass Effect 2', 'Action role-playing', 'Electronic Arts', 'PC, Xbox 360', 2010);
insert into games (nome, genere, publisher, platform, year) values ('Red Dead Redemption', 'Action-adventure', 'Rockstar Games', 'PlayStation 3, Xbox 360', 2010);
insert into games (nome, genere, publisher, platform, year) values ('Rock Band 3', 'Rhythm', 'MTV Games', 'Nintendo DS, PlayStation 3, Xbox 360, Wii', 2010);
insert into games (nome, genere, publisher, platform, year) values ('StarCraft II: Wings of Liberty', 'Real-time strategy', 'Blizzard Entertainment', 'PC, Macintosh', 2010);
insert into games (nome, genere, publisher, platform, year) values ('Super Mario Galaxy 2', 'Platform', 'Nintendo', 'Wii', 2010);
insert into games (nome, genere, publisher, platform, year) values ('Super Meat Boy', 'Platform', 'Team Meat', 'Xbox 360', 2010);
insert into games (nome, genere, publisher, platform, year) values ('Xenoblade Chronicles', 'Action role-playing', 'Nintendo', 'Wii', 2010);
insert into games (nome, genere, publisher, platform, year) values ('Batman: Arkham City', 'Action-adventure', 'Warner Bros. Interactive Entertainment', 'PlayStation 3, Xbox 360', 2011);
insert into games (nome, genere, publisher, platform, year) values ('Dark Souls', 'Action role-playing', 'Namco Bandai Games', 'PlayStation 3, Xbox 360', 2011);
insert into games (nome, genere, publisher, platform, year) values ('The Elder Scrolls V: Skyrim', 'Action role-playing', 'Bethesda Softworks', 'PC, PlayStation 3, Xbox 360', 2011);
insert into games (nome, genere, publisher, platform, year) values ('Minecraft', 'Sandbox', 'Mojang', 'PC', 2011);
insert into games (nome, genere, publisher, platform, year) values ('Portal 2', 'Puzzle-platformer', 'Valve', 'PC, PlayStation 3, Xbox 360', 2011);
insert into games (nome, genere, publisher, platform, year) values ('Dishonored', 'Stealth', 'Bethesda Softworks', 'PC, PlayStation 3, Xbox 360', 2012);
insert into games (nome, genere, publisher, platform, year) values ('Far Cry 3', 'First-person shooter', 'Ubisoft', 'PC, PlayStation 3, Xbox 360', 2012);
insert into games (nome, genere, publisher, platform, year) values ('Fire Emblem: Awakening', 'Tactical role-playing', 'Nintendo', 'Nintendo 3DS', 2012);
insert into games (nome, genere, publisher, platform, year) values ('Journey', 'Adventure', 'Sony Computer Entertainment', 'PlayStation 3', 2012);
insert into games (nome, genere, publisher, platform, year) values ('Hotline Miami', 'Action', 'Devolver Digital', 'PC', 2012);
insert into games (nome, genere, publisher, platform, year) values ('The Walking Dead', 'Adventure', 'Telltale Games', 'PC, PlayStation 3, Xbox 360', 2012);
insert into games (nome, genere, publisher, platform, year) values ('XCOM: Enemy Unknown', 'Turn-based strategy', '2K Games', 'PC, PlayStation 3, Xbox 360', 2012);
insert into games (nome, genere, publisher, platform, year) values ('BioShock Infinite', 'First-person shooter', '2K Games', 'PC, PlayStation 3, Xbox 360', 2013);
insert into games (nome, genere, publisher, platform, year) values ('Dota 2', 'MOBA', 'Valve', 'PC', 2013);
insert into games (nome, genere, publisher, platform, year) values ('Grand Theft Auto V', 'Action-adventure', 'Rockstar Games', 'PlayStation 3, Xbox 360', 2013);
insert into games (nome, genere, publisher, platform, year) values ('The Last of Us', 'Action-adventure', 'Sony Computer Entertainment', 'PlayStation 3', 2013);
insert into games (nome, genere, publisher, platform, year) values ('Papers, Please', 'Puzzle', '3909 LLC', 'PC, Macintosh', 2013);
insert into games (nome, genere, publisher, platform, year) values ('Destiny', 'First-person shooter', 'Bungie', 'PlayStation 3, PlayStation 4, Xbox 360, Xbox One', 2014);
insert into games (nome, genere, publisher, platform, year) values ('Shovel Knight', 'Platform', 'Yacht Club Games', 'Nintendo 3DS, PC, Wii U', 2014);
insert into games (nome, genere, publisher, platform, year) values ('Bloodborne', 'Action role-playing', 'Sony Computer Entertainment', 'PlayStation 4', 2015);
insert into games (nome, genere, publisher, platform, year) values ('Rocket League', 'Sports', 'Psyonix', 'PC, PlayStation 4', 2015);
insert into games (nome, genere, publisher, platform, year) values ('Undertale', 'Role-playing', 'Toby Fox', 'PC, Macintosh', 2015);
insert into games (nome, genere, publisher, platform, year) values ('The Witcher 3: Wild Hunt', 'Action role-playing', 'CD Projekt', 'PC, PlayStation 4, Xbox One', 2015);
insert into games (nome, genere, publisher, platform, year) values ('Inside', 'Platform', 'Playdead', 'Xbox One', 2016);
insert into games (nome, genere, publisher, platform, year) values ('Overwatch', 'First-person shooter', 'Blizzard Entertainment', 'PC, PlayStation 4, Xbox One', 2016);
insert into games (nome, genere, publisher, platform, year) values ('Stardew Valley', 'Simulation', 'ConcernedApe', 'PC', 2016);
insert into games (nome, genere, publisher, platform, year) values ('Uncharted 4: A Thief\'s End', 'Action-adventure', 'Sony Computer Entertainment', 'PlayStation 4', 2016);
insert into games (nome, genere, publisher, platform, year) values ('The Legend of Zelda: Breath of the Wild', 'Action-adventure', 'Nintendo', 'Nintendo Switch, Wii U', 2017);
insert into games (nome, genere, publisher, platform, year) values ('Super Mario Odyssey', 'Platform', 'Nintendo', 'Nintendo Switch', 2017);
insert into games (nome, genere, publisher, platform, year) values ('God of War', 'Action-adventure', 'Sony Interactive Entertainment', 'PlayStation 4', 2018);
insert into games (nome, genere, publisher, platform, year) values ('Red Dead Redemption 2', 'Action-adventure', 'Rockstar Games', 'PlayStation 4, Xbox One', 2018);
